version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:202004-01

    java:
      version: oraclejdk8

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ea:90:93:d8:34:4c:c0:bb:d2:0b:6d:1c:b7:8e:53:11"

      - run: python3 -m pip install pygments==2.6.1

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew website

      - run:
          command: .circleci/publish.sh

workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
